name: third
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: 3.2.3
  cupertino_icons: 1.0.6
  http: 0.13.6
  intl: 0.18.1
  json_annotation: 4.8.1
  provider: 6.1.2
  shared_preferences: 2.2.2
  uuid: 4.1.0
  go_router: 12.1.1
  collection: 1.18.0

dev_dependencies:
  flutter_lints: 2.0.3
  json_serializable: 6.6.2
  analyzer: 5.13.0
  matcher: 0.12.16
  build_runner: 2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/data.json